[package]
name = "cgroups"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
melon-common = {path = "../melon-common"}
tracing = { workspace = true }
